In [8]:
hist -n


   1: ?plot
   2: ?help
   3: help(help)
   4: ipython -pylab
   5: help(plot)
   6: hist -n
   7: hist
   8: hist -n


In [27]:
import numpy as np 
a=5
b=66
print(np.subtract(b,a))
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(b,a))
print(np.power(a,b))
print(np.remainder(b,a))
print(np.fmod(b,a))

61
71
330
13.2
-1319303399
1
1


In [32]:
import numpy as np

a=55
b=7
print(np.add(a,b))
print("equivalent to a+=b or a=a+b")

62
equivalent to a+=b or a=a+b


In [38]:
print("Relational operators in numpy : ")
a=44
b=33
print(np.equal(a,b))
print(np.greater(a,b))
print(np.not_equal(a,b))
print(np.greater_equal(a,b))
print(np.less_equal(a,b))

print("Fmod :")
print(np.fmod(a,b))

Relational operators
False
True
True
True
False
Fmod :
11


In [46]:
print("Logical operators in numpy : ")
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_xor(a,b))
print(np.logical_not(a))





Logical operators in numpy : 
True
True
False
False


In [61]:
from numpy import math
a=5
b=10
print("Root and logarithm  in numpy :")
print("SQRT of 3 is : ",np.math.sqrt(3),"\n")
print("log of 3 is ",np.math.log(3),"\n")
print("log10 of 3 is ",np.math.log10(3),"\n")
print("log base 2/binary of a is ",np.math.log(a,2),"\n")
print("exponential function : ")
print("exp of b is : ",np.math.exp(b)) 

Root and logarithm  in numpy :
SQRT of 3 is :  1.7320508075688772 

log of 3 is  1.0986122886681098 

log10 of 3 is  0.47712125471966244 

log base 2/binary of a is  2.321928094887362 

exponential function : 
exp of b is :  22026.465794806718


In [71]:
print("Round off in numpy :\n\n")

a=4.403445
b=9.4
c=6.6
d=7.7
print(np.around(a))
print(np.ceil(b))
print(np.floor(c))
print()
print("fix always rounds towards zero : ")
print(np.fix(d))

Round off in numpy :


4.0
10.0
6.0

fix always rounds towards zero : 
7.0


In [73]:
print("Mathematical constants : ")
print(math.pi)
print(math.e)
print(math.exp(1))

Mathematical constants : 
3.141592653589793
2.718281828459045
2.718281828459045


In [88]:
print("complex numbers in numpuy : ")
z=3+2j
print(z)
a=complex(2,5)
print(a)
print(abs(a))
print(a.real)
print(a.imag)
print(a.conjugate())

complex numbers in numpuy : 
(3+2j)
(2+5j)
5.385164807134504
2.0
5.0
(2-5j)


In [86]:
print("Missing part in numpy : ")
print("nan=not a number") 
print("inf = infinity") 
print("plus_inf") 
print("minus_inf") 
print("plus_zero") 
print("minus_zero") 

Missing part in numpy : 
nan=not a number
inf = infinity
plus_inf
minus_inf
plus_zero
minus_zero


In [94]:
print("Trigonmetry : ")

print("Hypotenus - euclidean distance : ")
print(np.hypot(4,5))
print("\n\n\narctangent is to check")

Trigonmetry : 
Hypotenus - euclidean distance : 
6.4031242374328485



arctangent is to check


In [111]:
print(np.random.random((6)).reshape(2,3))
print(np.random.uniform(2,5,6))

[[0.49210335 0.83086309 0.33545824]
 [0.80177436 0.82196373 0.8364195 ]]
5.2347921890915625
[3.49302837 3.52824389 4.4178156  3.87986777 2.0858419  4.46912099]


In [114]:
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [119]:
print(np.random.uniform(8))
print(np.random.uniform(0,6,(2,3)))


2.434019234921024
[[2.89119371 0.09301093 0.78873234]
 [3.49474248 0.16018322 0.9523864 ]]


In [123]:
print(np.random.standard_normal((5)))

[-2.07827241  0.75126003  0.9468519  -0.50737365  0.04187923]
